"""
Conversational Onboarding Tool for Artists

This script facilitates a voice-based onboarding conversation with an artist using a conversational AI model.
It records the user's voice input, transcribes it, generates AI responses, and recites them using text-to-speech.
The conversation history is maintained and saved at the end of the session.

Main Components:
- Environment setup and API key loading.
- Pydantic model for structured AI responses.
- Functions for speech synthesis (Azure TTS) and speech recognition (Azure Whisper + Cobra VAD).
- Conversation loop integrating LangChain, Cohere, and prompt templates.

Functions:
- recite_model_response(text): Converts a text response to speech using Azure TTS and plays it.
- record_and_transcribe(): Records audio from the microphone, detects end of speech, transcribes using Azure Whisper, and returns the recognized text.
- gather_information(): Manages the conversation loop, alternating between AI and user, and returns the full conversation history.

Usage:
Run this script directly to start the onboarding session. The conversation history is saved to 'conversation_history.txt'.
"""
## import dependencies
from langchain_openai import AzureChatOpenAI
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field
from langchain.prompts import PromptTemplate
from langchain_core.messages import HumanMessage, AIMessage, get_buffer_string
import pvcobra
import asyncio
from azure_agent_wrapper import onboarding_agent
import pyaudio
from pydub import AudioSegment
import io
import numpy as np
import requests
import wave

## environment setup
import os
from dotenv import load_dotenv
load_dotenv()

## define pydantic objects for structured output
class Response(BaseModel):
    message: str = Field(description="Response generated by the system")
    end_of_conversation: bool = Field(description="True if the conversation is finished else False means the conversation is to be continued")

## spech-to-text
def recite_model_response(text) -> None:
    """
    Convert a given text string to speech using Azure Text-to-Speech (TTS) and play the resulting audio.

    Args:
        text (str): The text to be synthesized and spoken aloud.

    Returns:
        None
    """
    AZURE_TTS_ENDPOINT = os.getenv("AZURE_TTS_ENDPOINT")
    AZURE_TTS_KEY = os.getenv("AZURE_TTS_KEY")
    # AZURE_TTS_LOCATION = os.getenv("AZURE_TTS_LOCATION", "eastus")
    url = f"{AZURE_TTS_ENDPOINT}/cognitiveservices/v1"
    ssml = f"""
    <speak version='1.0' xml:lang='en-US'>
        <voice name='en-US-AvaMultilingualNeural'>{text}</voice>
    </speak>
    """
    headers = {
        "Ocp-Apim-Subscription-Key": AZURE_TTS_KEY,
        "Content-Type": "application/ssml+xml",
        "X-Microsoft-OutputFormat": "audio-16khz-32kbitrate-mono-mp3",
        "User-Agent": "LangChain-TTS-Client"
    }

    response = requests.post(url, headers=headers, data=ssml.encode("utf-8"))

    if response.status_code == 200:
        mp3_audio = io.BytesIO(response.content)
        mp3_audio.seek(0)

        # Playback using pydub + pyaudio
        speech = AudioSegment.from_file(mp3_audio, format="mp3")
        p = pyaudio.PyAudio()
        stream = p.open(
            format=p.get_format_from_width(speech.sample_width),
            channels=speech.channels,
            rate=speech.frame_rate,
            output=True
        )
        stream.write(speech.raw_data)
        stream.stop_stream()
        stream.close()
        p.terminate()
    else:
        print("Azure TTS Error:", response.status_code, response.text)

## recording and text-to-speech
def record_and_transcribe() -> str:
    """
    Record audio from the user's microphone, detect the end of speech using Cobra VAD,
    and transcribe the recorded audio to text using Azure Whisper.

    Returns:
        str: The transcribed text from the user's spoken input.
    """
    cobra = pvcobra.create(access_key=os.getenv('PVCOBRA_ACCESS_TOKEN'))

    ## mic recording parameters
    FORMAT = pyaudio.paInt16
    CHANNELS = 1
    RATE = 16000
    FRAMES_PER_BUFFER = 512

    audio = pyaudio.PyAudio()
    stream = audio.open(
        format=FORMAT,
        channels=CHANNELS,
        rate=RATE,
        frames_per_buffer=FRAMES_PER_BUFFER,
        input=True
    )

    frames = []
    pause_seconds = 3
    nbuffers = int(np.ceil(1 / (FRAMES_PER_BUFFER / RATE) * pause_seconds))

    def get_next_audio_frame():
        audio_data = stream.read(FRAMES_PER_BUFFER, exception_on_overflow=False)
        return np.frombuffer(audio_data, dtype=np.int16)

    try:
        print("Start Recording!!")
        counter = 0
        while True:
            audio_frame = get_next_audio_frame()
            frames.append(audio_frame)
            voice_prob = cobra.process(audio_frame)
            if voice_prob < 0.1:
                counter += 1
            else:
                counter = 0
            if counter >= nbuffers:
                print("Finished Recording!")
                break
    except KeyboardInterrupt:
        print("Interrupted!")
    finally:
        stream.stop_stream()
        stream.close()
        audio.terminate()
        cobra.delete()

        ## convert to WAV in memory (**can't pass numpy array directly)
        audio_array = np.concatenate(frames, axis=0).astype(np.int16)
        wav_bytes = io.BytesIO()
        with wave.open(wav_bytes, 'wb') as wf:
            wf.setnchannels(CHANNELS)
            wf.setsampwidth(audio.get_sample_size(FORMAT))
            wf.setframerate(RATE)
            wf.writeframes(audio_array.tobytes())
        wav_bytes.seek(0)

        azure_endpoint = os.getenv("AZURE_WHISPER_ENDPOINT")
        azure_api_key = os.getenv("AZURE_WHISPER_KEY")

        files = {"file": ("audio.wav", wav_bytes, "audio/wav")}
        headers = {"api-key": azure_api_key}
        response = requests.post(azure_endpoint, headers=headers, files=files)

        if response.status_code == 200:
            result = response.json()
            return result.get("text", "")
        else:
            print("Azure Whisper Error:", response.status_code, response.text)
            return ""

def gather_information() -> str:
    """
    Conduct a conversational onboarding session with the user.

    Repeatedly prompts the user for input (via speech), generates AI responses,
    recites them, and maintains the conversation history. Ends when the AI signals
    the end of the conversation.

    Returns:
        str: The complete conversation history as a formatted string.
    """
    conversation_history = []
    ## set up prompt, output parser, LLM
    with open(r"src\tools\prompts\OnboardingMayaPrompt.txt", "r", encoding="utf-8") as file:
        prompt_template = file.read()
    parser = JsonOutputParser(pydantic_object=Response)
    system_prompt = PromptTemplate(
        template=prompt_template,
        input_variables=["conversation_history"],
        partial_variables={"format_instructions": parser.get_format_instructions()}
    )
    chatmodel = AzureChatOpenAI(
        openai_api_key=os.environ["AZURE_OPENAI_KEY"],
        azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
        azure_deployment=os.environ["AZURE_OPENAI_DEPLOYMENT"],
        openai_api_version=os.environ["AZURE_OPENAI_API_VERSION"]
    )
    chain = system_prompt | chatmodel | parser

    ## conversation loop
    while True:
        ## model response -> recite response through some TTS model
        response = chain.invoke({"conversation_history": conversation_history})
        conversation_history.append(AIMessage(content=response['message']))
        recite_model_response(response['message'])

        if response['end_of_conversation']:
            ## will remove the print portion later
            print("END OF SESSION".center(60, "-"))
            print("\n\n")
            print("CONVERSATION HISTORY".center(40, "#"))
            for message in conversation_history:
                print(f">> {message.type}: {message.content}", end="\n")
            break
        ## user response -> record him/herself
        user_response = record_and_transcribe()
        conversation_history.append(HumanMessage(content=user_response))
    
    return get_buffer_string(conversation_history)

async def run_agent(agent, task_template, message_source, input_text):
    task = task_template.format(input_text)
    result = await agent.run(task=task)
    for message in result.messages:
        if getattr(message, "source", None) == message_source:
            return message.content

if __name__=="__main__":
   conv_history = gather_information()
   print(" Conversation History ".center(30,"-"))
   print(conv_history)
   onboarding_agent_template = "Save the data of the following user: {}"
   onboarding_agent_result = asyncio.run(
    run_agent(
        agent=onboarding_agent,
        task_template=onboarding_agent_template,
        message_source="onboarding_agent",
        input_text=conv_history
    )
)

#    with open(r"example_delete_later\conversation_history.txt", "w", encoding="utf-8") as file:
#     file.write(conv_history)