## import dependencies
from langchain_cohere import ChatCohere
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field
from langchain.prompts import PromptTemplate
from langchain_core.messages import HumanMessage, AIMessage
from langchain.schema.messages import get_buffer_string
from gtts import gTTS
import whisper
import pvcobra
import pyaudio
from pydub import AudioSegment
from io import BytesIO
import numpy as np
from json import dumps
import warnings

## filter torch user warning
warnings.filterwarnings("ignore", message="FP16 is not supported on CPU; using FP32 instead")

## environment setup
import os
from dotenv import load_dotenv
load_dotenv()
os.environ['COHERE_API_KEY'] = os.getenv('COHERE_API_KEY')

## define pydantic objects for structured output
class Response(BaseModel):
    message: str = Field(description="Response generated by the system")
    end_of_conversation: bool = Field(description="True if the conversation is finished else False means the conversation is to be continued")

class UserProfile(BaseModel):
    name_of_the_artist: str = Field(description="The full name of the artist as mentioned in the conversation")
    location: str = Field(description="Where the artist usually creates or showcases their art (e.g., city, street, area)", default="Unknown")
    language_preference: str = Field(description="The language the artist is most comfortable using for online content", default="Unknown")
    type_of_art: str = Field(description="A short description of the kind of art they create (e.g., murals, sketches, folk art)")
    years_of_experience: str = Field(description="How long the artist has been practicing their craft", default="Unknown")
    artist_story: str = Field(description="A brief background or origin story shared by the artist about their journey", default="Unknown")
    why_they_want_to_be_online: str = Field(description="The artist's motivation for building an online presence (e.g., reach more people, earn better)", default="Unknown")
    is_open_to_custom_orders: bool = Field(description="Whether the artist is willing to take on commissions or personalized art requests")

def recite_model_response(text):
    recitation = gTTS(text=text, tld="co.in", lang="en", lang_check=False)

    mp3_file_object = BytesIO()
    recitation.write_to_fp(fp=mp3_file_object)
    mp3_file_object.seek(0)
    
    speech = AudioSegment.from_file(
        format="mp3",
        file=mp3_file_object
    )
    p = pyaudio.PyAudio()
    stream = p.open(
        format=p.get_format_from_width(speech.sample_width),
        channels=speech.channels,
        rate=speech.frame_rate,
        output=True
    )
    stream.write(speech.raw_data)
    stream.stop_stream()
    stream.close()
    p.terminate()

def record_and_trascribe():
    cobra = pvcobra.create(access_key=os.getenv('PVCOBRA_ACCESS_TOKEN'))
    stt_model = whisper.load_model("small", device="cpu")
   
    ## properties of audio-signal
    FORMAT = pyaudio.paInt16
    CHANNEL = 1
    RATE = 16000
    FRAMES_PER_BUFFER = 512

    audio = pyaudio.PyAudio()
    stream = audio.open(
        format=FORMAT,
        channels=CHANNEL,
        rate=RATE,
        frames_per_buffer=FRAMES_PER_BUFFER,
        input=True
    )
    frames = []
    pause_seconds = 3
    nbuffers = int(np.ceil(1/(FRAMES_PER_BUFFER/RATE)*pause_seconds))

    def get_next_audio_frame():
        audio_data = stream.read(FRAMES_PER_BUFFER, exception_on_overflow=False)
        audio_frame = np.frombuffer(audio_data, dtype=np.int16)
        return audio_frame
    
    try:
        print("Start Recording!!")
        counter = 0
        while True:
            audio_frame = get_next_audio_frame()
            frames.append(audio_frame)
            voice_prob = cobra.process(audio_frame)
            if voice_prob < 0.1:
                counter += 1
            else:
                counter = 0
            if counter >= nbuffers:
                print("Finished Recording!")
                break
    except KeyboardInterrupt:
        print("Interrupted!")
    finally:
        stream.stop_stream()
        stream.close()
        audio.terminate()
        cobra.delete()
        
        audio_array = np.concatenate(frames, axis=0).astype(np.float32)
        audio_array /= np.max(np.absolute(audio_array))
        transcription = stt_model.transcribe(audio_array, )['text']
        return transcription

def gather_information():
    conversation_history = []
    ## set up prompt, output parser, LLM
    with open(r"src\tools\prompts\final-output-system-prompt.txt", "r", encoding="utf-8") as file:
        prompt_template = file.read()
    parser = JsonOutputParser(pydantic_object=Response)
    system_prompt = PromptTemplate(
        template=prompt_template,
        input_variables=["conversation_history"],
        partial_variables={"format_instructions": parser.get_format_instructions()}
    )
    chatmodel = ChatCohere()
    chain = system_prompt | chatmodel | parser

    ## conversation loop
    while True:
        ## model response -> recite response through some TTS model
        response = chain.invoke({"conversation_history": conversation_history})
        conversation_history.append(AIMessage(content=response['message']))
        recite_model_response(response['message'])

        if response['end_of_conversation']:
            ## will remove the print portion later
            print("END OF SESSION".center(60, "-"))
            print("\n\n")
            print("CONVERSATION HISTORY".center(40, "#"))
            for message in conversation_history:
                print(f">> {message.type}: {message.content}", end="\n")
            break
        ## user response -> record him/herself
        user_response = record_and_trascribe()
        conversation_history.append(HumanMessage(content=user_response))
    
    return conversation_history

def get_final_user_profile():
    conversation_history = get_buffer_string(gather_information())
    with open(r"src\tools\prompts\final-output-system-prompt.txt", "r") as file:
        system_prompt_template = file.read()
    parser = JsonOutputParser(pydantic_object=UserProfile)
    final_system_prompt = PromptTemplate(
        template=system_prompt_template,
        input_variables=["conversation_history"],
        partial_variables={"format_instructions": parser.get_format_instructions()}
    )
    chatmodel = ChatCohere()
    chain = final_system_prompt | chatmodel | parser
    user_profile_info = chain.invoke({"conversation_history": conversation_history})
    return dumps(user_profile_info)    

if __name__=="__main__":
    final_output = get_final_user_profile()
    print("\n\n\n")
    print(final_output)